# permissions for end users to view vifpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vifpool-viewer-role
rules:
- apiGroups:
  - network.wooshnet.cn
  resources:
  - vifpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.wooshnet.cn
  resources:
  - vifpools/status
  verbs:
  - get
