# permissions for end users to edit wooshports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wooshport-editor-role
rules:
- apiGroups:
  - network.wooshnet.cn
  resources:
  - wooshports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.wooshnet.cn
  resources:
  - wooshports/status
  verbs:
  - get
