FROM alpine:3.13

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN echo "export LC_ALL=zh_CN.UTF8" >> /etc/profile
RUN apk add git tzdata socat make bash zstd util-linux curl
ENV TZ Asia/Shanghai